[project]
name = 'flash_loan_provider'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.flash_loan]
path = 'contracts/flash_loan.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
